#!/bin/bash
# Apollo Client + Vite Compatibility Patch
# Generated by Antigravity

echo "🔍 Patching GraphQL generated files for Vite compatibility..."

# Focus on ALL files in the generated directory
GENERATED_DIR="src/modules/graphql/generated"

if [ -d "$GENERATED_DIR" ]; then
    for FILE in "$GENERATED_DIR"/*.ts; do
        if [ -f "$FILE" ]; then
            echo "  - Patching $FILE"
            
            # 1. Change to 'import type' for @graphql-typed-document-node/core
            sed -i '' "s|import { \(.*\) } from '@graphql-typed-document-node/core'|import type { \1 } from '@graphql-typed-document-node/core'|g" "$FILE"
            
            # 2. Change to 'import type' for graphql package types
            sed -i '' "s|import { \(.*\) } from 'graphql'|import type { \1 } from 'graphql'|g" "$FILE"
            
            # 3. Specific fix for TypedDocumentNode as DocumentNode pattern
            sed -i '' "s|import { TypedDocumentNode as DocumentNode }|import type { TypedDocumentNode as DocumentNode }|g" "$FILE"

            # 4. Fix Incremental import in fragment-masking.ts
            sed -i '' "s|import { Incremental } from './graphql'|import type { Incremental } from './graphql'|g" "$FILE"
            
            # 5. Fix ResultOf and other types in index.ts if they are being imported as values
            sed -i '' "s|import { \(FragmentType, useFragment, makeFragmentData, isFragmentReady\) } from './fragment-masking'|import { \1 } from './fragment-masking'|g" "$FILE"
            # (Wait, these ARE functions, so they should NOT be 'import type')
        fi
    done
fi

echo "✅ Patch applied successfully."
